public class apexclassexample {

   /* public Account acc {set;get;}
    
    public apexclassexample(){
        acc = new Account();
        acc.Name='Go of Thunder';
        acc.AnnualRevenue=1201233;
        acc.AccountSource='web';
        acc.Phone='787887889';
        
        
    }*/
    
    public static string hi (string name, string city , string nation){
        
        string adress = ('Your name is :'+name+ ' your city is '+city+' your naton is '+nation);
       
            return adress;
     
    }
}